### ISSUE TITLE
测试 visualize 目录下文件发现的问题

### ISSUE THREAD

**Issue by O-O1024** [seasonSH/SemanticStyleGAN#9]
1、没有把项目根目录添加到 sys.path，根本无法 import，我就是在项目根目录运行的

2、invert.py 文件有很多问题！！！

2.1、args.device、args.truncation_mean、lpips.PerceptualLoss 都是未定义的。lpips下也没找到 PerceptualLoss，是不是 readme 文件写漏了一些步骤？

2.2、truncation_mean 怎么用来生成随机数了
g_ema = g_ema.style(torch.randn(args.truncation_mean<<<===, g_ema.style_dim, device=device)).mean(0)

**Comment by seasonSH** [comment]
1. please run the scripts under the root folder
2. the inversion script was updated after I uploaded it. The current version should not have these problems.
